version: "3.7"
services:
  app:
    build:
      context: .
      # target: build
    volumes:
      - "./config.yml:/app/config.yml"
    environment:
      DEBUG: "${DEBUG:-false}"
      APP_PORT: "${APP_PORT:-8000}"
    ports:
      - "${APP_PORT:-8000}:${APP_PORT:-8000}"
